# fly.toml app configuration file generated for datingapp2 on 2024-04-12T13:33:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingapp2'
primary_region = 'mad'

[build]
  image = 'kaprim/datingapp:latest'

[env]
  ASPNETCORE_URLS='http://+:8080'
  CloudinarySettings__CloudName='djkulxmzt'
  CloudinarySettings__ApiKey='988952821186855'
 
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http-checks = []
  internal_port = 8080
  processes = ['app']
  protocol = 'tcp'
  script_checks = []
   [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"


[[services.ports]]
  force_https = true
  handlers = ['http']
  port = 80
